### ISSUE TITLE
データベースの名前を決めましょう

### ISSUE THREAD

**Issue by ndac-todoroki** [Phi-phi/oop-server#2]
- どんなテーブル、フィールドがあったらいいか
- どんな名前がいいか

とか

**Comment by ndac-todoroki** [comment]
とりあえず
- 送られてきたMACアドレスとかを保存するためのテーブル
- MACアドレスとその位置のデータベースのためのテーブル
  は要りそうな

**Comment by ndac-todoroki** [comment]
送信者の情報(端末MACアドレス)を保持する `users`
MACアドレス一覧を保存する `access_points` (固定)
教室の情報を保持する `classes` (固定)

```
classes has_many :access_points
access_points belongs_to :classes
```

```
users has_one :access_points   #(とりあえずは)
users has_many :access_points  #(のちのち：アクセスポイントをスキャンするようになったらこうする必要があるかも　計算して一つに絞ってから保存するなら上のままで良い)
access_points belongs_to :users

users has_many :classes, through: :access_points
classes has_many :users, through: :access_points
```

こんな感じでどうだろう

**Comment by ndac-todoroki** [comment]
教室の情報 `classes` だと `class Class` になって大変なことになると判明したので変えてみた

``` ruby
class Classroom < ActiveRecord::Base
  has_many :access_points
  has_many :users, through: :access_points
end
```

``` ruby
class User < ActiveRecord::Base
  has_one :access_points
  has_many :classrooms, through: :access_points
end
```

``` ruby
class AccessPoint < ActiveRecord::Base
  belongs_to :classrooms
  belongs_to :users
end
```

**Comment by Phi-phi** [comment]
返答おくれてごめんなさいー
それで大丈夫だと思う
ただ教室とユーザって多対多？

**Comment by ndac-todoroki** [comment]
これもしかして通知行ってないんじゃないかなって思ってめっちゃassignmentいじってしまった(笑)

Phi-phi wrote:

> ただ教室とユーザって多対多？

あーーーーーーーーー

``` ruby
class User < ActiveRecord::Base
  has_one :access_points
  delegate :classrooms, through: :access_points
end
```

でいいのかな…

**Comment by Phi-phi** [comment]
delegateはtoだから、そこを直せばおkじゃね？
まあhas_one throughでもいいのか

**Comment by Phi-phi** [comment]
ごめんねーなぜかunwatchにしてたw

**Comment by ndac-todoroki** [comment]
Phi-phi wrote::

> delegateはtoだから、そこを直せばおkじゃね？
> まあhas_one throughでもいいのか

has_one throughのほうがパット見わかりやすそうだから動作上同じならこっちにしますかー

アクセスポイントが複数ユーザー持てること忘れてた
あと単数複数ミスってるから最終的にはこんな感じに

``` ruby
class Classroom < ActiveRecord::Base
  has_many :access_points
  has_many :users, through: :access_points
end

class AccessPoint < ActiveRecord::Base
  belongs_to :classroom
  has_many :users
end

class User < ActiveRecord::Base
  belongs_to :access_point
  has_one :classroom, through: :access_point
end
```

頭がごちゃごちゃしてきました…

**Comment by Phi-phi** [comment]
あ、やってくれる？
ありがとー

**Comment by Phi-phi** [comment]
Userがふたつ？

ごめん嘘。治ってた

**Comment by Phi-phi** [comment]
フィールドに関してはぱっと思いつく限り、
userはユーザー名、macaddr,
classroomは名前、位置情報（緯度経度？）
apは名前、macadr
でいいかな？

**Comment by ndac-todoroki** [comment]
1. Classroom
   - (id)
   - name (string)
   - location (text, serializeオプションを付加しておいて緯度経度のArrayを渡すのがいいのかな)  
2. AccessPoint
   - (id)
   - macaddr (string)
   - classroom_id (integer)
3. User
   - (id)
   - macaddr (string)
   - access_point_id (integer)

**Comment by ndac-todoroki** [comment]
あ、スク言の課題的には過去のデータ見れるといい感じな気がするので Log みたいなテーブルもなんとなく作っておくかもしれません(OOPの課題とはとりあえず関係ない)

Log
- (id)
- data(text, serialize)

**Comment by Phi-phi** [comment]
logてどのレベルの記録？
ある程度ならrailsのログファイル見ればいっかなーなんて思うんだけど

**Comment by ndac-todoroki** [comment]
何月何日の混雑状況を取得、とか、３０分毎のλ館の利用者変遷をグラフにとかどうだろうって

**Comment by Phi-phi** [comment]
なるほどーはあく
ならプロセス4,5あたりに挟めばいいかな？
一応ログだし確認もかねてユーザとか教室あたりも紐付けとくか

**Comment by ndac-todoroki** [comment]
Logとりあえず単独で作っちゃった、まぁ後からでもテーブルいじれるし
でも紐付けってどうしようかしら…

**Comment by Phi-phi** [comment]
めんどくさいしリレーションシップでよくね

**Comment by Phi-phi** [comment]
あ、あとできたコミットプッシュしてくれない？どのあたり自分作業すればいいのかはあくしときたい

**Comment by ndac-todoroki** [comment]
プッシュはしたけどちょっとまだプルリク送ってない状態　ReadMeとかいじってる間に寝てしまったすまない

**Comment by ndac-todoroki** [comment]
プルリク送りました。OKなら(Logとか他のテーブルに関してはu-doryの個人的な課題なので)ひとまずissueも閉じてしまっていいかも
残ってる作業は送受信Controllerの追加及びルーティング(+私はViewも)だと思うのでそれは別トピックな感じで
